### PR TITLE
ensure data/priority position in hgetall result

### LINKED ISSUE #129: use redis as persistent queue in gearman (v1.1.16)
If somebody use redis as persistent queue in gearman，be aware of configuration `hash_max_ziplist_value` about redis, otherwise you may get some errors when you restart gearmand.

```shell
Begin stack trace, frames found: 17
?0  0x7f6a6cdaa9b3 in /usr/local/gearman/sbin/gearmand(+0x1b9b3) [0x7f6a6cdaa9b3]
?1  0x7f6a6cd99bd7 in /usr/local/gearman/sbin/gearmand(+0xabd7) [0x7f6a6cd99bd7]
?2  0x7f6a6b5007e0 in /lib64/libpthread.so.0(+0xf7e0) [0x7f6a6b5007e0]
#3  0x7f6a6a3965e5 in gsignal at /lib64/libc.so.6
#4  0x7f6a6a397dc5 in abort at /lib64/libc.so.6
---> demangled: __gnu_cxx::__verbose_terminate_handler() -> __gnu_cxx::__verbose_terminate_handler()
#5  0x7f6a6ac50a7d in __gnu_cxx::__verbose_terminate_handler() at /usr/lib64/libstdc++.so.6
?6  0x7f6a6ac4ebd6 in /usr/lib64/libstdc++.so.6(+0xbcbd6) [0x7f6a6ac4ebd6]
?7  0x7f6a6ac4ec03 in /usr/lib64/libstdc++.so.6(+0xbcc03) [0x7f6a6ac4ec03]
?8  0x7f6a6ac4ed22 in /usr/lib64/libstdc++.so.6(+0xbcd22) [0x7f6a6ac4ed22]
---> demangled: std::__throw_invalid_argument(char const*) -> std::__throw_invalid_argument(char const*)
#9  0x7f6a6abf3f57 in std::__throw_invalid_argument(char const*) at /usr/lib64/libstdc++.so.6
?10  0x7f6a6cdb817e in /usr/local/gearman/sbin/gearmand(+0x2917e) [0x7f6a6cdb817e]
?11  0x7f6a6cdb835c in /usr/local/gearman/sbin/gearmand(+0x2935c) [0x7f6a6cdb835c]
?12  0x7f6a6cdb5f3c in /usr/local/gearman/sbin/gearmand(+0x26f3c) [0x7f6a6cdb5f3c]
?13  0x7f6a6cdad4e7 in /usr/local/gearman/sbin/gearmand(+0x1e4e7) [0x7f6a6cdad4e7]
?14  0x7f6a6cda54ec in /usr/local/gearman/sbin/gearmand(+0x164ec) [0x7f6a6cda54ec]
#15  0x7f6a6a382d1d in __libc_start_main at /lib64/libc.so.6
?16  0x7f6a6cd99a05 in /usr/local/gearman/sbin/gearmand(+0xaa05) [0x7f6a6cd99a05]
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
```

### PR DESCRIPTION
**Pull request by p-alik**
aims to fix #129

### CODE REVIEW

**Comment by SpamapS** [comment]
recheck

File: libgearman-server/plugins/queue/redis/queue.cc [hunk 1]
```diff
@@ -153,9 +153,19 @@ bool gearmand::plugins::queue::Hiredis::fetch(char *key, gearmand::plugins::queu
...
+      std::string s{reply->element[1]->str};
+      req.data = s;
+      req.priority = (uint32_t)std::stoi(reply->element[3]->str);
+    } else if (strcmp(fk, "priority") == 0) {
+      std::string s{reply->element[3]->str};
+      req.data = s;
+      req.priority = (uint32_t)std::stoi(reply->element[1]->str);
+    } else {
+      std::string ex{"unexpected key at first position in "};
+      throw std::invalid_argument(ex.append(key));
```
Comment (SpamapS) [inline libgearman-server/plugins/queue/redis/queue.cc]: We've never thrown exceptions before in any plugins. This throw is going to crash the thread and really all of gearmand. I know this happens only on startup, but it's a pretty nasty way to explode.

I suggest instead we return false, which the code handles well and which will tell the user which key failed.

Comment (p-alik) [inline libgearman-server/plugins/queue/redis/queue.cc]: exception is replaced by error logging as requested
